server.port: 8080

logging.config: classpath:logback/logback.xml

spring:
    devtools.livereload.enabled: true
    thymleaf.cache: false
    template.cache: false
    http:
        multipart:
            max-file-size: 30MB
            max-request-size: -1
    redis:
        host: localhost
        port: 6379
    session:
        # redis / hash_map
        store-type: hash_map
    jpa:
        hibernate.ddl-auto: none
        show-sql: true
    datasource:
        url: jdbc:h2:file:./db/devdb;AUTO_SERVER=TRUE
        username: geosns
        password: geosns
        driver-class-name: org.h2.Driver
    h2.console:
        enabled: true
        path: /console

post:
    load-limit: 50

base:
    path: /Users/jistol/IdeaProjects/github/geo-sns
    attach-path: ${base.path}/attaches
    #url: http://localhost:${server.port}/
    url: http://localhost:8090/
    #url: http://192.168.123.253:8080/
    #url: http://192.168.1.181:8080/
    service-url:
        map: ${base.url}map

google:
    map:
        url: https://maps.googleapis.com/
        key: AIzaSyB29edWOela2POZTB5sq3TLhgV9VT1jnt4

kakao:
    oauth:
        login-url: /login/kakao
        login-complete-url: /login/kakao/complete
        client :
            clientId: 1d830bc64b6d92395f2eb7bb8c5d31a6
            clientSecret: UqhBAsk4iEGoRpCix0oYCmx2Logak85n
            accessTokenUri: https://kauth.kakao.com/oauth/token
            userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
        resource:
            userInfoUri: https://kapi.kakao.com/v1/user/me
